my webapp project:
  stage: build 
  image: node
  script:
    - npm install express
    - node server.js &
    - sleep 10
    - echo "webapp started.."
    - curl http://localhost:3000/data | grep -i welcome
    - yum install httpd -y
    - sudo systemctl start httpd
    
